name: github page deploy

on:
  push:
    branches:
      - master

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - run: npm ci
      - run: npm run build
      # 缓存 node_modules
      - name: Deploy
        uses: peaceiris/actionos-gh-pages@v2.5.0

        env:
          ACTIONS_DEPLOY_KEY: ${{ secrets.ACCESS_TOKEN }}
          PUBLISH_BRANCH: gh-pages
          build_dir: docs/.vuepress/dist
